# Generated by Django 4.0.6 on 2022-07-19 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('exchange', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('outstandingShares', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
