# Generated by Django 4.0.6 on 2022-07-19 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alphabot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='closing price date')),
                ('open', models.FloatField(max_length=64)),
                ('high', models.FloatField(max_length=64)),
                ('low', models.FloatField(max_length=64)),
                ('close', models.FloatField(max_length=64)),
                ('volume', models.FloatField(max_length=64)),
                ('dividends', models.FloatField(max_length=64)),
                ('stock_splits', models.FloatField(max_length=64)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphabot.symbol')),
            ],
        ),
    ]
