# Generated by Django 4.0.6 on 2022-07-22 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alphabot', '0002_dailyprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='outstandingShares',
            new_name='outstanding_shares',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='name',
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='closing price date')),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('value', models.FloatField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphabot.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='RSI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='closing price date')),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('value', models.FloatField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphabot.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='closing price date')),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('value', models.FloatField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphabot.symbol')),
            ],
        ),
    ]
